sonarr:
  sonarr:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - config: /config/includes/web-720p-v4.yml

    quality_profiles:
      - name: Remux 2160p
        reset_unmatched_scores:
          enabled: true
          except:
            - "!Blocked Terms"
            - "!Not Original Language"
        upgrade:
          allowed: true
          until_quality: Bluray-2160p Remux
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p Remux
          - name: Bluray-1080p Remux

      - name: Bluray 2160p
        reset_unmatched_scores:
          enabled: true
          except:
            - "!BHDStudio"
            - "!Not Original Language"
            - "!UHD Bluray Tier 01"
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: Bluray-1080p

      - name: WEB-2160p
        reset_unmatched_scores:
          enabled: true
          except:
            - "!BHDStudio"
            - "!Not Original Language"
        upgrade:
          allowed: true
          until_quality: WEB 2160p
          until_score: 10000
        min_format_score: 0
        qualities:
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-1080p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
          - name: HDTV-1080p
          - name: HDTV-720p
          - name: Bluray|WEB-480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
              - Bluray-480p
          - name: DVD

      - name: WEB-1080p
        reset_unmatched_scores:
          enabled: true
          except:
            - "!BHDStudio"
            - "!Not Original Language"
        upgrade:
          allowed: true
          until_quality: WEB 1080p
          until_score: 10000
        min_format_score: 0
        qualities:
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-1080p
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
          - name: HDTV-1080p
          - name: HDTV-720p
          - name: Bluray|WEB-480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
              - Bluray-480p
          - name: DVD

      - name: WEB-720p
        reset_unmatched_scores:
          enabled: true
          except:
            - "!BHDStudio"
            - "!Not Original Language"
        upgrade:
          allowed: true
          until_quality: WEB 720p
          until_score: 10000
        min_format_score: 0
        qualities:
          - name: WEB 720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
          - name: WEB 1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
          - name: Bluray-720p
          - name: Bluray-1080p
          - name: HDTV-1080p
          - name: HDTV-720p
          - name: Bluray|WEB-480p
            qualities:
              - WEBDL-480p
              - WEBRip-480p
              - Bluray-480p
          - name: DVD

    delete_old_custom_formats: true
    # replace_existing_custom_formats: true

    custom_formats:
      - trash_ids:
          # Audio
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
        quality_profiles:
          - { name: WEB-2160p, score: 35 }
          - { name: WEB-1080p, score: 35 }
          - { name: WEB-720p, score: 35 }

      - trash_ids:
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
        quality_profiles:
          - { name: WEB-2160p, score: 25 }
          - { name: WEB-1080p, score: 25 }
          - { name: WEB-720p, score: 25 }

      - trash_ids:
          - dbe00161b08a25ac6154c55f95e6318d # DD
        quality_profiles:
          - { name: WEB-2160p, score: 15 }
          - { name: WEB-1080p, score: 15 }
          - { name: WEB-720p, score: 15 }

      - trash_ids:
          # Groups
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
        quality_profiles:
          - name: WEB-2160p
          - name: WEB-1080p
          - name: WEB-720p

      - trash_ids:
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02

          # Versions
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
        quality_profiles:
          - name: Remux 2160p

      - trash_ids:
          # HD Bluray Tier Groups
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
        quality_profiles:
          - name: Bluray 2160p

      - trash_ids:
          # Unwanted
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        quality_profiles:
          - name: Remux 2160p
          - name: Bluray 2160p
          - name: WEB-2160p
          - name: WEB-1080p
          - name: WEB-720p

      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
        quality_profiles:
          - name: Remux 2160p
          - name: Bluray 2160p
          - name: WEB-2160p

      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
        quality_profiles:
          - { name: Remux 2160p, score: 0 }
          - { name: Bluray 2160p, score: 0 }
          - { name: WEB-2160p, score: 0 }

      - trash_ids:
          - 7ba05c6e0e14e793538174c679126996 # Multi
        quality_profiles:
          - { name: Remux 2160p, score: -10000 }
          - { name: Bluray 2160p, score: -10000 }
          - { name: WEB-2160p, score: -10000 }
          - { name: WEB-1080p, score: -10000 }
          - { name: WEB-720p, score: -10000 }

      - trash_ids:
          # Streaming Services
          - bbcaf03147de0f73be2be4a9078dfa03 # 4OD
          - fcc09418f67ccaddcf3b641a22c5cfd7 # ALL4
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 4e9a630db98d5391aec1368a0256e2fe # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7be9c0572d8cd4f81785dacf7e85985e # FOD
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - 4404ad44d87ccbb82746e180713112fb # HTSR
          - f6cce30f1733d5c8194222a7507909bb # Hulu
          - dc503e2425126fa1d0a9ad6168c83b3f # iP
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - fa5a16b951004c23e980d2913694a137 # ITVX
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - b2b980877494b560443631eb1f473867 # NLZ
          - fb1a91cdc0f26f7ca0696e0e95274645 # OViD
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          - d100ea972d1af2150b65b1cffb80f6b5 # TVer
          - 0e99e7cc719a8a73b2668c3a0c3fe10c # U-NEXT
          - 5d2317d99af813b6529c7ebf01c83533 # VDL
          - 93c9d1e566dca8b34d57f5efbbf85f28 # VIU
          - 43b3cf48cb385cd3eac608ee6bca7f09 # UHD Streaming Boost
          - d2d299244a92b8a52d4921ce3897a256 # UHD Streaming Cut

          # HDR Metadata
          - 2b239ed870daba8126a53bd5dc8dc1c8 # DV HDR10Plus
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - bb019e1cd00f304f80971c965de064dc # HDR (undefined)
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HDR
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - a3d82cbef5039f8d295478d28a887159 # HDR10+
          - 17e889ce13117940092308f48b48b45b # HLG
          - 2a7e3be05d3861d6df7171ec74cad727 # PQ

          # Audio
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD Atmos
          - 9d00418ba386a083fbf4d58235fc37ef # DTS X
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
          - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
          - 30f70576671ca933adbdcfc736a69718 # PCM
          - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - c1a25cd67b5d2e08287c957b1eb903ec # DTS-ES
          - 5964f2a8b3be407d083498e4459d05d0 # DTS
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
          - dbe00161b08a25ac6154c55f95e6318d # DD

          # Repacks / Propers
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3

          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
        quality_profiles:
          - name: Remux 2160p
          - name: Bluray 2160p
